=== skoma123/CMSTest/CMS/MEL/747 Rev51.0 2012_1_31/Working/melcdl.dtd
<?xml version="1.0" encoding="utf-8"?>
<!NOTATION GIF SYSTEM "GIF"                                       >
<!NOTATION TIF SYSTEM "TIF"                                       >
<!NOTATION JPG SYSTEM "JPG"                                       >

<!NOTATION PNG SYSTEM "PNG"                                       >
<!NOTATION cgm PUBLIC
"-//USA-DOD//NOTATION Computer Graphics Metafile//EN"             >
  
<!NOTATION ccitt4 PUBLIC
"-//USA-DOD//NOTATION CCITT Group 4 Facsimile//EN"                >

<!ENTITY % ATIeqn1 PUBLIC "-//ArborText//ENTITIES Equation1//EN//XML" "entities/ati-eqn1.ent">
<!ENTITY % ISOamsa PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Arrow Relations//EN//XML" "entities/iso-amsa.ent"  >
<!ENTITY % ISOamsb PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Binary Operators//EN//XML" "entities/iso-amsb.ent"  >
<!ENTITY % ISOamsc PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Delimiters//EN//XML" "entities/iso-amsc.ent"  >
<!ENTITY % ISOamsn PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Negated Relations//EN//XML" "entities/iso-amsn.ent"  >
<!ENTITY % ISOamso PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Ordinary//EN//XML" "entities/iso-amso.ent"  >
<!ENTITY % ISOamsr PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Relations//EN//XML" "entities/iso-amsr.ent"  >
<!ENTITY % ISObox  PUBLIC "ISO 8879:1986//ENTITIES Box and Line Drawing//EN//XML" "entities/iso-box.ent"  >
<!ENTITY % ISOcyr1 PUBLIC "ISO 8879:1986//ENTITIES Russian Cyrillic//EN//XML" "entities/iso-cyr1.ent"  >
<!ENTITY % ISOcyr2 PUBLIC "ISO 8879:1986//ENTITIES Non-Russian Cyrillic//EN//XML" "entities/iso-cyr2.ent"  >
<!ENTITY % ISOdia  PUBLIC "ISO 8879:1986//ENTITIES Diacritical Marks//EN//XML" "entities/iso-dia.ent"  >
<!ENTITY % ISOgrk1 PUBLIC "ISO 8879:1986//ENTITIES Greek Letters//EN//XML" "entities/iso-grk1.ent"  >
<!ENTITY % ISOgrk2 PUBLIC "ISO 8879:1986//ENTITIES Monotoniko Greek//EN//XML" "entities/iso-grk2.ent"  >
<!ENTITY % ISOgrk3 PUBLIC "ISO 8879:1986//ENTITIES Greek Symbols//EN//XML" "entities/iso-grk3.ent"  >
<!ENTITY % ISOgrk4 PUBLIC "ISO 8879:1986//ENTITIES Alternative Greek Symbols//EN//XML" "entities/iso-grk4.ent"  >
<!ENTITY % ISOlat1 PUBLIC "ISO 8879:1986//ENTITIES Added Latin 1//EN//XML" "entities/iso-lat1.ent"  >
<!ENTITY % ISOlat2 PUBLIC "ISO 8879:1986//ENTITIES Added Latin 2//EN//XML" "entities/iso-lat2.ent"  >
<!ENTITY % ISOnum  PUBLIC "ISO 8879:1986//ENTITIES Numeric and Special Graphic//EN//XML" "entities/iso-num.ent"  >
<!ENTITY % ISOpub  PUBLIC "ISO 8879:1986//ENTITIES Publishing//EN//XML" "entities/iso-pub.ent"  >
<!ENTITY % ISOtech PUBLIC "ISO 8879:1986//ENTITIES General Technical//EN//XML" "entities/iso-tech.ent"  >
<!ENTITY % HTMLlat1x PUBLIC "-//W3C//ENTITIES Latin1//EN//HTML" "entities/HTMLlat1x.ent" >
<!ENTITY % HTMLsymbolx PUBLIC "-//W3C//ENTITIES Symbols//EN//HTML" "entities/HTMLsymbolx.ent">
<!ENTITY % HTMLspecialx PUBLIC "-//W3C//ENTITIES Special//EN//HTML" "entities/HTMLspecialx.ent">

%ATIeqn1; %ISOamsa; %ISOamsb; %ISOamsc; %ISOamsn; %ISOamso; %ISOamsr; %ISObox; %ISOcyr1; %ISOcyr2;
%ISOdia; %ISOgrk1; %ISOgrk2; %ISOgrk3; %ISOgrk4; %ISOlat1; %ISOlat2; %ISOnum; %ISOpub; %ISOtech;
%HTMLlat1x; %HTMLsymbolx; %HTMLspecialx;

<!ENTITY   % w.c     "(warning*,caution*)"                        >

<!ENTITY   % text
       "para|table|unlist|numlist|glosdata|
         warning|caution|note|exception|example|ops"              >

<!ENTITY % revatt     "chg          (N|R|U|D)       'N'
                       key           ID             #REQUIRED
                       revnbr        CDATA          #REQUIRED
                       revdate       NMTOKEN        #REQUIRED" >

<!ENTITY % yesorno    "NMTOKEN" >
<!ELEMENT melcdl         (legalntc?, revdata?, mel, dmp, cdl)                  >

<!ATTLIST melcdl  
	  model          CDATA          #REQUIRED
          mantype       (MELCDL)        'MELCDL'
          oidate         NMTOKEN        #REQUIRED
          tsn            CDATA          #REQUIRED
          docnbr         CDATA          #IMPLIED
          lang           CDATA          #REQUIRED
          cus            CDATA          #REQUIRED
          spl            CDATA          #IMPLIED
	  chg          (N|R|U|D)        'N'
          key           ID              #REQUIRED
          revdate       NMTOKEN         #REQUIRED
          faadate       NMTOKEN         #IMPLIED
          mmelrevnbr    CDATA           #REQUIRED                    >

<!ELEMENT legalntc  (chgdesc*, proptary?, cpyrght?, geninfo?)     >
<!ATTLIST legalntc
          key           ID             #REQUIRED                  >

<!ELEMENT proptary  (title?, para+)                               >
<!ELEMENT cpyrght   (year?, holder+)                              >
<!ELEMENT year      (#PCDATA)                                     >
<!ELEMENT holder    (#PCDATA)                                     >
<!ELEMENT geninfo   (title?,(%text;)+)           	          >


<!ELEMENT revdata (coverpage?, recrev, transmittal)               >
<!ELEMENT coverpage  (para+)           	                  >  
<!ELEMENT recrev  (title?,(%text;)+)           	                  >
<!ATTLIST recrev   chg          (N|R|U|D)       'N'
                   revdate       NMTOKEN        #REQUIRED         >

<!ELEMENT transmittal  (title?,(%text;|graphic)+)           	  >

<!ELEMENT mel  (title, mfmatr, chapter*)                             >

<!ATTLIST mel
 	  %revatt;				                     >

<!ELEMENT cdl  (title, mfmatr?, chapter*)                            >

<!ATTLIST cdl
 	  %revatt;				                     >

<!ELEMENT dmp  (title, mfmatr?)                                      >

<!ATTLIST dmp
 	  %revatt;				                     >


<!ELEMENT mfmatr (section+)               		             >

<!ATTLIST mfmatr       
	  %revatt;					             >

<!ELEMENT chapter  (chgdesc*, title, ecam?)	     >

<!ATTLIST chapter	
	  chapnbr     NMTOKEN      #REQUIRED
	  %revatt;				>

<!ELEMENT ecam		(chgdesc*, ecam_group+)                      >

<!ATTLIST ecam		
	  chapnbr     NMTOKEN      #REQUIRED
 	  %revatt;				                     >
          
<!ELEMENT ecam_group	(fltmsg_category, ecam_warning+)	     >

<!ELEMENT fltmsg_category  (#PCDATA) 				     >
	  
<!ELEMENT ecam_warning	(ecam_fltmsg, ecam_dispcond, ecam_remark)    >

<!ELEMENT ecam_fltmsg	(#PCDATA) 				     >
								
<!ELEMENT ecam_dispcond	(para+) 			             >
									
<!ELEMENT ecam_remark	(%text;)+ 			             >

<!ELEMENT section    (chgdesc*,  title?, (item+ | textset+ 
                                            | (cdlblk, note*)+))       >
<!ATTLIST section	
	  chapnbr	NMTOKEN	  #REQUIRED
	  sectnbr	NMTOKEN	  #REQUIRED
	  %revatt;				>


<!ELEMENT textset    (chgdesc*, title?, (%text;|graphic|textgrp|revision)+) >
<!ATTLIST textset
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  textsetnbr NMTOKEN       #REQUIRED
          %revatt;		             >
<!ELEMENT textgrp   (title?,(%text;|graphic|textgrp|revision)+)   >
<!ATTLIST textgrp
          tip       %yesorno;                         #IMPLIED   
          textgrpnbr NMTOKEN                          #IMPLIED    >

<!ELEMENT cdlblk    (chgdesc*, title?, remarks, (%text;|act | graphic 
                              | textgrp | revision)*)   >
<!ATTLIST cdlblk
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  %revatt;
	  blknbr     NMTOKEN       #IMPLIED
	  qtyreq     CDATA         #IMPLIED
	  attr-rev   (YES|NO)      "NO"                           >
																  

<!ELEMENT glosdata  (term, def)                                   >
<!ELEMENT term      (#PCDATA|sub|super)*                          >
<!ELEMENT def       (#PCDATA|sub|super)*                          >

<!ELEMENT item       (effect*, chgdesc*, title?, dispcond?, graphic*)	>

<!ATTLIST item	     
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  itemnbr    NMTOKEN       #IMPLIED
	  %revatt;					>

<!ELEMENT dispcond   (remarks?, operation?, limitation?, placard?, maintenance?)>
<!ATTLIST dispcond	
	  category         CDATA        #IMPLIED
	  nbrins           CDATA        #IMPLIED
	  nbrreq           CDATA        #IMPLIED
	  maintenance      (YES|NO)      "NO"
	  operation        (YES|NO)      "NO"
		downgrade        CDATA        #IMPLIED
	  attr-rev        (YES|NO)      "NO"           >

<!ELEMENT remarks      (%text;|revision)*				>

<!ELEMENT placard	(%text;|revision)* 					>

<!ELEMENT maintenance	(title?,(%text;|act|graphic|revision)*) 					>
<!ATTLIST maintenance
          key           ID             #REQUIRED	>

<!ELEMENT operation	(%text;|act|graphic|revision)*					>
<!ATTLIST operation
          key           ID             #REQUIRED	>

<!ELEMENT limitation	(%text;|act|graphic|revision)* 					>
<!ATTLIST limitation
          key           ID             #REQUIRED	>

<!ELEMENT act (challenge,response+,comment*) >
<!ATTLIST act
          responsible (F|CF|PM|C|PF|SO) #IMPLIED>

<!ELEMENT challenge (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT response (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT comment (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT unlist    (unlitem+)                                    >
<!ATTLIST unlist
          bulltype  (NONE|BULLET|NDASH|MDASH
                     |DIAMOND|ASTERISK|DELTA
                     |SQUARE|SYSTEM1)                  'SYSTEM1'    >

<!ELEMENT unlitem   (para|note|example|exception|graphic|unlist)+ >

<!ELEMENT numlist   (numlitem+)                                   >
<!ATTLIST numlist
          numtype   (NNP|AUP|NNB|ALB|NNS|RUP|RLP|RUR|RLR|NNR
                      |AUR|ALR)                       'NNP'       >

<!ELEMENT numlitem  (%text;|graphic)+                             >


<!ELEMENT para      (#PCDATA  | grphcref | refext | refint
                         | sub | super | emphasis | revision)*       >

<!ELEMENT sub       (#PCDATA)                                     >
<!ELEMENT super     (#PCDATA)                                     >

<!ELEMENT emphasis (#PCDATA|emphasis)*                            >
<!ATTLIST emphasis
          role (bold|underline|italic)                 "italic"   >


<!ELEMENT title     (#PCDATA|sub|super|revision)*		  >
<!ELEMENT warning   (para | unlist | numlist)+                    >
<!ELEMENT note      (para | unlist | numlist)+                    >
<!ELEMENT caution   (para | unlist | numlist)+                    >
<!ELEMENT exception (para | unlist | numlist)+                    >
<!ELEMENT example   (para | unlist | numlist)+                    >

<!ELEMENT  ops		(ops_type, ops_message)>
<!ELEMENT  ops_type	(#PCDATA)	>
<!ELEMENT  ops_message	(#PCDATA)	>

<!ELEMENT effect    EMPTY                           >
<!ATTLIST effect
          effrg     CDATA                             "001999"
          efftext   CDATA                             "ALL"
          chg       (N|R|U|D)                         'U'         >


<!ELEMENT refext    (#PCDATA)                                     >
<!ATTLIST refext
          refman    CDATA                             #IMPLIED
          refspl    CDATA                             #IMPLIED
          refmodel  CDATA                             #IMPLIED
          docnbr    CDATA                             #IMPLIED
          refloc    CDATA                             #IMPLIED    >

<!ELEMENT refint    (#PCDATA)                                     >
<!ATTLIST refint
          reftype   CDATA                             #IMPLIED
          refid     IDREF                             #IMPLIED    >


<!ELEMENT grphcref  (#PCDATA | effect)*                           >
<!ATTLIST grphcref
          refid     IDREF                             #IMPLIED
          sheetnbr  CDATA                             #IMPLIED
          structid  CDATA                             #IMPLIED
          shownow   %yesorno;                         '0'         >

<!ELEMENT graphic   (effect?, title?, (sheet | revision)*)        >
<!ATTLIST graphic
          chapnbr     NMTOKEN                        #IMPLIED
          sectnbr     NMTOKEN                        #IMPLIED
          confnbr     NMTOKEN                        #IMPLIED
          %revatt;                                                >

<!ELEMENT sheet     (effect?, title?)                             >
<!ATTLIST sheet
          gnbr      ENTITY                            #IMPLIED
          filename  CDATA                             #IMPLIED
          sheetnbr  CDATA                             #IMPLIED
          imgarea   (AP|BP|CP|DL|EL|FP|GP|HL|IL)      #IMPLIED
          width     CDATA                             #IMPLIED
          height    CDATA                             #IMPLIED
          %revatt;                                                >


<!ELEMENT revision (#PCDATA|para|graphic|sheet|emphasis|revision|sub|super)* >
<!ATTLIST revision
          chg     (insert|delete|modify)              "modify"    >

<!ELEMENT chgdesc   (#PCDATA|emphasis|sub|super)*                 >



<!ENTITY % bodyatt "">
<!ENTITY % secur "">


<!ENTITY % yesorno 'CDATA'>
<!ENTITY % titles  'title?'>


<!ENTITY % paracon '#PCDATA'>

<!ENTITY % tbl.table.name       "(table|chart)">
<!ENTITY % tbl.table-titles.mdl "%titles;,">
<!ENTITY % tbl.table-main.mdl   "(tgroup+|graphic+)">
<!ENTITY % tbl.table.mdl        "%tbl.table-titles.mdl; %tbl.table-main.mdl;">
<!ENTITY % tbl.table.att        '
    tabstyle    CDATA           #IMPLIED
    tocentry    %yesorno;       #IMPLIED
    shortentry  %yesorno;       #IMPLIED
    orient      (port|land)     #IMPLIED
    pgwide      %yesorno;       #IMPLIED '>
<!ENTITY % tbl.tgroup.mdl       "colspec*,spanspec*,thead?,tfoot?,tbody">
<!ENTITY % tbl.tgroup.att       '
    tgroupstyle CDATA           #IMPLIED '>
<!ENTITY % tbl.hdft.mdl         "colspec*,row+">
<!ENTITY % tbl.row.mdl          "(entry|entrytbl)+">
<!ENTITY % tbl.entrytbl.mdl     "colspec*,spanspec*,thead?,tbody">
<!ENTITY % tbl.entry.mdl        "(%text;)*">

<!ELEMENT table (%tbl.table.mdl;)>
<!ATTLIST table
        frame           (top|bottom|topbot|all|sides|none)      #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        %tbl.table.att;
        %bodyatt;
        %secur;
>

<!ELEMENT tgroup (%tbl.tgroup.mdl;) >

<!ATTLIST tgroup
        cols            CDATA                                   #REQUIRED
        %tbl.tgroup.att;
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        %secur;
>

<!ELEMENT colspec EMPTY >

<!ATTLIST colspec
        colnum          CDATA                                   #IMPLIED
        colname         CDATA                                   #IMPLIED
        colwidth        CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
>

<!ELEMENT spanspec EMPTY >

<!ATTLIST spanspec
        namest          CDATA                                   #REQUIRED
        nameend         CDATA                                   #REQUIRED
        spanname        CDATA                                   #REQUIRED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
>

<!ELEMENT thead (%tbl.hdft.mdl;)>
<!ATTLIST thead
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT tfoot (%tbl.hdft.mdl;)>
<!ATTLIST tfoot
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT tbody (row+)>

<!ATTLIST tbody
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT row (%tbl.row.mdl;)>

<!ATTLIST row
        rowsep          %yesorno;                               #IMPLIED
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT entrytbl (%tbl.entrytbl.mdl;)>

<!ATTLIST entrytbl
        cols            CDATA                                   #REQUIRED
        %tbl.tgroup.att;
        colname         CDATA                                   #IMPLIED
        spanname        CDATA                                   #IMPLIED
        namest          CDATA                                   #IMPLIED
        nameend         CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        %secur;
>

<!ELEMENT entry (%tbl.entry.mdl;)*>

<!ATTLIST entry
        colname         CDATA                                   #IMPLIED
        namest          CDATA                                   #IMPLIED
        nameend         CDATA                                   #IMPLIED
        spanname        CDATA                                   #IMPLIED
        morerows        CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        rotate          %yesorno;                               #IMPLIED
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

=== skoma123/CMSTest/CMS/MEL/747/UPS747MEL20070815102847.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="26" chg="U" itemnbr="2-1-2" key="UPS747MEL20070815102847" revdate="20100707" revnbr="8" sectnbr="14">
<!--Per C.R.4342 Tim 1/21/10 for Rev 8-->
<effect chg="U" effrg="" efftext="N570UP-N577UP and N580UP-N583UP">
</effect>
<title>Crew Rest Area Smoke Detection System</title>
<dispcond category="C" maintenance="YES" nbrins="3" nbrreq="1"
operation="YES" btb="YES">
<remarks>
<para>Two may be inoperative provided:</para>
<numlist>
<numlitem><para>Center detector is operative, and</para></numlitem>
<numlitem><para>Associated detector(s) is deactivated.</para></numlitem>
</numlist>
</remarks>
<operation key="UPS747MEL20070815102848">
<numlist>
<numlitem><para>If any crew rest area is placarded CREW REST AREA
SMOKE DET SYS INOP &ndash; DO NOT ENTER, do not use the affected crew
rest area for any purpose.</para></numlitem>
</numlist>
</operation>
<limitation key="UPS747-400MELCDL20080702152142">
<note><para>International flights may be affected if crew rest area
or supernumerary seats are deemed unusable.</para></note>
</limitation>
<placard>
<para>Placard below Captain&rsquo;s PFD on P-1-1 panel: "CREW REST
AREA SMOKE DET SYS INOP". Enter Item in Aircraft Deferred Item Log.</para>
</placard>
<maintenance key="UPS747MEL20070815102849">
<numlist>
<numlitem><para>Confirm normal detector operation by noting the following
while the self test switch on detector&rsquo;s faceplate is depressed:</para>
<numlist>
<numlitem><para>Caution message> SMOKE CREW REST displays on EICAS.</para>
</numlitem>
<numlitem><para>The detector&rsquo;s alarm horn sounds off.</para>
</numlitem>
</numlist>
</numlitem>
<numlitem><para>For each inoperative detector:</para>
<numlist>
<numlitem><para>Disconnect, cap and stow the inoperative detector&rsquo;s
electrical connector (AMM 26-14-21, page 401).</para></numlitem>
<numlitem><para>Crew Rest Area smoke detectors are identical and interchangeable.
If the center detector (STA 595, BL 0, WL 391) is inoperative, it
may be interchanged with an operable detector from a bunk bed room.</para>
</numlitem>
</numlist>
</numlitem>
</numlist>
<graphic chapnbr="26" chg="U" key="UPS747MEL20070815102850"
revdate="20080827" revnbr="5" sectnbr="14">
<sheet chg="U" gnbr="747-400_DMP_CH_26_Page_5"
key="UPS747MEL20070815102851" revdate="20080827" revnbr="5"></sheet>
</graphic>
</maintenance>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/757/Working/UPS-757-MEL-00000158.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="21" chg="U" itemnbr="3" key="UPS-757-MEL-00000158" revdate="20080924" revnbr="65" sectnbr="52">
<title>Air Conditioning Pack OFF Lights</title>
<dispcond btb="NO" category="C" maintenance="YES" nbrins="2" nbrreq="1"
operation="NO">
<remarks>
<para>One may be inoperative OFF provided associated EICAS message
and all other pack indications are operative.</para>
</remarks>
<placard>
<para>Placard affected OFF light "INOP" and enter item in Aircraft
Deferred Item Log.</para>
</placard>
<maintenance key="UPS-757-MEL-00000159">
<numlist>
<numlitem><para>Provide electric and pneumatic power.</para></numlitem>
<numlitem><para>Make sure affected pack L (R) PACK OFF advisory message
is displayed on upper EICAS (pack off). (NOTE: press RECALL as necessary
to display message.)</para></numlitem>
<numlitem><para>Select affected pack to AUTO.</para></numlitem>
<numlitem><para>Make sure affected pack advisory message is not displayed. </para>
</numlitem>
<numlitem><para>Select affected pack to OFF.</para></numlitem>
<numlitem><para>Make sure affected pack L (R) PACK OFF advisory message
is displayed.</para></numlitem>
<numlitem><para>Return aircraft to desired configuration.</para>
</numlitem>
</numlist>
</maintenance>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/757/Working/UPS-MEL-757-344301001FDK.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="34" chg="U" itemnbr="1-0-1" key="UPS-MEL-757-344301001FDK" revdate="20100423" revnbr="68" sectnbr="43">
<title>Weather Radar System</title>
<dispcond category="C" nbrins="1" nbrreq="0" operation="NO">
<remarks>
<para>May be inoperative for day VMC. May be inoperative for day IMC
and night (VMC or IMC) provided that no thunderstorms or other potentially
hazardous weather conditions, detectable with airborne weather radar,
may reasonably be expected along the route of flight.</para>
</remarks>
<operation key="UPS-MEL-757-3443101OPSFDK">
<note><para>No aircraft shall be dispatched in day IMC or night (VMC
or IMC) when current weather reports indicate thunderstorms or other
potentially hazardous weather conditions, detectable with airborne
weather radar, may reasonably be expected along the route of flight
unless approved airborne radar equipment is installed in the aircraft
and is in satisfactory operating condition.</para></note>
<para>During daylight hours, when pilot reports or current weather
reports indicate widely scattered thunderstorm activity which may
be circumnavigated visually, operative radar is not a requirement
for the release of a flight.</para>
<para>Although the requirements for operative radar are based on current
weather reports, consideration shall also be given to forecasts and
other indications of the need for operative radar en route.</para>
</operation>
<limitation key="UPS-MEL-757-3443101LIMFDK">
<numlist>
<!--Per Ken Foster's e-mail 2/1/10-->
<numlitem><para>Dispatch not authorized when thunderstorms or other
potentially hazardous weather conditions can be detected with airborne
weather radar may reasonably be expected along the route to be flown.</para>
</numlitem>
</numlist>
<note><para>Dispatch allowed when the flight is planned to avoid any
potential thunderstorms or hazardous weather.</para></note>
</limitation>
<placard>
<para>Placard Weather Radar Control Panel (M75) located on P8 panel
"INOP" and enter item in Aircraft Deferred Item Log.</para>
</placard>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/747/Staging/UPS747-400MELCDL20080714152625.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="26" chg="U" itemnbr="1-4-4" key="UPS747-400MELCDL20080714152625" revdate="20080827" revnbr="5"
sectnbr="23">
<effect effrg="578579" efftext=""></effect>
<title>Lower Cargo Compartment Fire Extinguisher System &ndash; Six
Bottle System, Bottles C, D, E &amp; F</title>
<dispcond category="C" nbrins="4" nbrreq="0" operation="YES">
<remarks>
<para>All bottles and associated indications may be inoperative provided:</para>
<numlist>
<numlitem><para>Aircraft is operated pressurized,</para></numlitem>
<numlitem><para>For Combi, procedures are established and used to
verify main deck cargo compartment remains empty or contains only
empty cargo handling equipment, ballast (ballast may be loaded in
ULD's), or fly away kits, and</para></numlitem>
<numlitem><para>Flight remains within 20 minutes of landing at a suitable
airport.</para></numlitem>
</numlist>
</remarks>
<operation key="UPS747-400MELCDL20080709144013">
<note><para>The following EICAS message(s) may be displayed:</para>
<para>BTL LOW CARGO ___</para>
</note>
<numlist>
<numlitem><para>Operate Aircraft in pressurized condition.</para>
</numlitem>
</numlist>
</operation>
<limitation key="UPS747-400MELCDL20080709144121">
<numlist>
<numlitem><para>Flight remains within 20 minutes of landing at a suitable
airport.</para></numlitem>
</numlist>
</limitation>
<placard>
<para>Placard adjacent or on fire control module located on pilots
overhead panel "LOWER CARGO COMP FIRE EXT SYST INOP". Enter item in
Aircraft Deferred Item Log.</para>
</placard>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/747/Staging/UPS747MEL20070815101733.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="21" chg="U" itemnbr="1-1" key="UPS747MEL20070815101733" revdate="20080827" revnbr="5" sectnbr="58">
<title>Equipment Cooling Control System &ndash; NORM Mode </title>
<dispcond category="C" maintenance="NO" nbrins="1" nbrreq="0"
operation="YES" btb="NO">
<remarks>
<para>May be inoperative provided:</para>
<numlist>
<numlitem><para>STBY mode is used, and</para></numlitem>
<numlitem><para>For ground operation above 105&deg;F OAT (41&deg;C)
at least one pack is operative.</para></numlitem>
</numlist>
</remarks>
<operation key="UPS747MEL20070815101734">
<numlist>
<numlitem><para>Select STBY mode.</para></numlitem>
<numlitem><para>Ensure at least one pack is operating for ground operation
above 105&deg;F OAT (41&deg;C).</para></numlitem>
</numlist>
</operation>
<placard>
<para>Placard adjacent to the Equipment Cooling selector "NORM INOP".
 Enter item in Aircraft Deferred Item Log.</para>
</placard>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/747 MEL Rev51.0 2012_1_31/Working/UPS747MEL20070815102711.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="25" chg="U" itemnbr="2" key="UPS747MEL20070815102711" revdate="20080827" revnbr="5" sectnbr="40">
<title>Lavatory Waste Receptacle Access Doors/ Covers</title>
<dispcond category="C" maintenance="YES" nbrins="1" nbrreq="0">
<remarks>
<para>May be inoperative provided:</para>
<numlist>
<numlitem><para>Associated waste container is empty,</para></numlitem>
<numlitem><para>Receptacle access is secured to prevent waste introduction
into the receptacle,</para></numlitem>
<numlitem><para>Lavatory is used only by crewmembers, and</para>
</numlitem>
<numlitem><para>Associated lavatory entrance door is locked closed
and placarded, INOPERATIVE &ndash; DO NOT ENTER.</para></numlitem>
</numlist>
<note><para>These provisions are not intended to prohibit lavatory
use or inspections by crewmembers.</para></note>
</remarks>
<placard>
<para>Placard adjacent to the waste access door "DO NOT USE" and enter
item in Aircraft Deferred Item Log.</para>
</placard>
<maintenance key="UPS747MEL20070815102712">
<numlist>
<numlitem><para>Ensure waste receptacle is empty.</para></numlitem>
<numlitem><para>Block access door with tape.</para></numlitem>
</numlist>
</maintenance>
</dispcond>
</item>
