=== skoma123/CMSTest/CMS/MEL/747 Rev51.0 2012_1_31/Working/melcdl.dtd
<?xml version="1.0" encoding="utf-8"?>
<!NOTATION GIF SYSTEM "GIF"                                       >
<!NOTATION TIF SYSTEM "TIF"                                       >
<!NOTATION JPG SYSTEM "JPG"                                       >

<!NOTATION PNG SYSTEM "PNG"                                       >
<!NOTATION cgm PUBLIC
"-//USA-DOD//NOTATION Computer Graphics Metafile//EN"             >
  
<!NOTATION ccitt4 PUBLIC
"-//USA-DOD//NOTATION CCITT Group 4 Facsimile//EN"                >

<!ENTITY % ATIeqn1 PUBLIC "-//ArborText//ENTITIES Equation1//EN//XML" "entities/ati-eqn1.ent">
<!ENTITY % ISOamsa PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Arrow Relations//EN//XML" "entities/iso-amsa.ent"  >
<!ENTITY % ISOamsb PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Binary Operators//EN//XML" "entities/iso-amsb.ent"  >
<!ENTITY % ISOamsc PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Delimiters//EN//XML" "entities/iso-amsc.ent"  >
<!ENTITY % ISOamsn PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Negated Relations//EN//XML" "entities/iso-amsn.ent"  >
<!ENTITY % ISOamso PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Ordinary//EN//XML" "entities/iso-amso.ent"  >
<!ENTITY % ISOamsr PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Relations//EN//XML" "entities/iso-amsr.ent"  >
<!ENTITY % ISObox  PUBLIC "ISO 8879:1986//ENTITIES Box and Line Drawing//EN//XML" "entities/iso-box.ent"  >
<!ENTITY % ISOcyr1 PUBLIC "ISO 8879:1986//ENTITIES Russian Cyrillic//EN//XML" "entities/iso-cyr1.ent"  >
<!ENTITY % ISOcyr2 PUBLIC "ISO 8879:1986//ENTITIES Non-Russian Cyrillic//EN//XML" "entities/iso-cyr2.ent"  >
<!ENTITY % ISOdia  PUBLIC "ISO 8879:1986//ENTITIES Diacritical Marks//EN//XML" "entities/iso-dia.ent"  >
<!ENTITY % ISOgrk1 PUBLIC "ISO 8879:1986//ENTITIES Greek Letters//EN//XML" "entities/iso-grk1.ent"  >
<!ENTITY % ISOgrk2 PUBLIC "ISO 8879:1986//ENTITIES Monotoniko Greek//EN//XML" "entities/iso-grk2.ent"  >
<!ENTITY % ISOgrk3 PUBLIC "ISO 8879:1986//ENTITIES Greek Symbols//EN//XML" "entities/iso-grk3.ent"  >
<!ENTITY % ISOgrk4 PUBLIC "ISO 8879:1986//ENTITIES Alternative Greek Symbols//EN//XML" "entities/iso-grk4.ent"  >
<!ENTITY % ISOlat1 PUBLIC "ISO 8879:1986//ENTITIES Added Latin 1//EN//XML" "entities/iso-lat1.ent"  >
<!ENTITY % ISOlat2 PUBLIC "ISO 8879:1986//ENTITIES Added Latin 2//EN//XML" "entities/iso-lat2.ent"  >
<!ENTITY % ISOnum  PUBLIC "ISO 8879:1986//ENTITIES Numeric and Special Graphic//EN//XML" "entities/iso-num.ent"  >
<!ENTITY % ISOpub  PUBLIC "ISO 8879:1986//ENTITIES Publishing//EN//XML" "entities/iso-pub.ent"  >
<!ENTITY % ISOtech PUBLIC "ISO 8879:1986//ENTITIES General Technical//EN//XML" "entities/iso-tech.ent"  >
<!ENTITY % HTMLlat1x PUBLIC "-//W3C//ENTITIES Latin1//EN//HTML" "entities/HTMLlat1x.ent" >
<!ENTITY % HTMLsymbolx PUBLIC "-//W3C//ENTITIES Symbols//EN//HTML" "entities/HTMLsymbolx.ent">
<!ENTITY % HTMLspecialx PUBLIC "-//W3C//ENTITIES Special//EN//HTML" "entities/HTMLspecialx.ent">

%ATIeqn1; %ISOamsa; %ISOamsb; %ISOamsc; %ISOamsn; %ISOamso; %ISOamsr; %ISObox; %ISOcyr1; %ISOcyr2;
%ISOdia; %ISOgrk1; %ISOgrk2; %ISOgrk3; %ISOgrk4; %ISOlat1; %ISOlat2; %ISOnum; %ISOpub; %ISOtech;
%HTMLlat1x; %HTMLsymbolx; %HTMLspecialx;

<!ENTITY   % w.c     "(warning*,caution*)"                        >

<!ENTITY   % text
       "para|table|unlist|numlist|glosdata|
         warning|caution|note|exception|example|ops"              >

<!ENTITY % revatt     "chg          (N|R|U|D)       'N'
                       key           ID             #REQUIRED
                       revnbr        CDATA          #REQUIRED
                       revdate       NMTOKEN        #REQUIRED" >

<!ENTITY % yesorno    "NMTOKEN" >
<!ELEMENT melcdl         (legalntc?, revdata?, mel, dmp, cdl)                  >

<!ATTLIST melcdl  
	  model          CDATA          #REQUIRED
          mantype       (MELCDL)        'MELCDL'
          oidate         NMTOKEN        #REQUIRED
          tsn            CDATA          #REQUIRED
          docnbr         CDATA          #IMPLIED
          lang           CDATA          #REQUIRED
          cus            CDATA          #REQUIRED
          spl            CDATA          #IMPLIED
	  chg          (N|R|U|D)        'N'
          key           ID              #REQUIRED
          revdate       NMTOKEN         #REQUIRED
          faadate       NMTOKEN         #IMPLIED
          mmelrevnbr    CDATA           #REQUIRED                    >

<!ELEMENT legalntc  (chgdesc*, proptary?, cpyrght?, geninfo?)     >
<!ATTLIST legalntc
          key           ID             #REQUIRED                  >

<!ELEMENT proptary  (title?, para+)                               >
<!ELEMENT cpyrght   (year?, holder+)                              >
<!ELEMENT year      (#PCDATA)                                     >
<!ELEMENT holder    (#PCDATA)                                     >
<!ELEMENT geninfo   (title?,(%text;)+)           	          >


<!ELEMENT revdata (coverpage?, recrev, transmittal)               >
<!ELEMENT coverpage  (para+)           	                  >  
<!ELEMENT recrev  (title?,(%text;)+)           	                  >
<!ATTLIST recrev   chg          (N|R|U|D)       'N'
                   revdate       NMTOKEN        #REQUIRED         >

<!ELEMENT transmittal  (title?,(%text;|graphic)+)           	  >

<!ELEMENT mel  (title, mfmatr, chapter*)                             >

<!ATTLIST mel
 	  %revatt;				                     >

<!ELEMENT cdl  (title, mfmatr?, chapter*)                            >

<!ATTLIST cdl
 	  %revatt;				                     >

<!ELEMENT dmp  (title, mfmatr?)                                      >

<!ATTLIST dmp
 	  %revatt;				                     >


<!ELEMENT mfmatr (section+)               		             >

<!ATTLIST mfmatr       
	  %revatt;					             >

<!ELEMENT chapter  (chgdesc*, title, ecam?)	     >

<!ATTLIST chapter	
	  chapnbr     NMTOKEN      #REQUIRED
	  %revatt;				>

<!ELEMENT ecam		(chgdesc*, ecam_group+)                      >

<!ATTLIST ecam		
	  chapnbr     NMTOKEN      #REQUIRED
 	  %revatt;				                     >
          
<!ELEMENT ecam_group	(fltmsg_category, ecam_warning+)	     >

<!ELEMENT fltmsg_category  (#PCDATA) 				     >
	  
<!ELEMENT ecam_warning	(ecam_fltmsg, ecam_dispcond, ecam_remark)    >

<!ELEMENT ecam_fltmsg	(#PCDATA) 				     >
								
<!ELEMENT ecam_dispcond	(para+) 			             >
									
<!ELEMENT ecam_remark	(%text;)+ 			             >

<!ELEMENT section    (chgdesc*,  title?, (item+ | textset+ 
                                            | (cdlblk, note*)+))       >
<!ATTLIST section	
	  chapnbr	NMTOKEN	  #REQUIRED
	  sectnbr	NMTOKEN	  #REQUIRED
	  %revatt;				>


<!ELEMENT textset    (chgdesc*, title?, (%text;|graphic|textgrp|revision)+) >
<!ATTLIST textset
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  textsetnbr NMTOKEN       #REQUIRED
          %revatt;		             >
<!ELEMENT textgrp   (title?,(%text;|graphic|textgrp|revision)+)   >
<!ATTLIST textgrp
          tip       %yesorno;                         #IMPLIED   
          textgrpnbr NMTOKEN                          #IMPLIED    >

<!ELEMENT cdlblk    (chgdesc*, title?, remarks, (%text;|act | graphic 
                              | textgrp | revision)*)   >
<!ATTLIST cdlblk
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  %revatt;
	  blknbr     NMTOKEN       #IMPLIED
	  qtyreq     CDATA         #IMPLIED
	  attr-rev   (YES|NO)      "NO"                           >
																  

<!ELEMENT glosdata  (term, def)                                   >
<!ELEMENT term      (#PCDATA|sub|super)*                          >
<!ELEMENT def       (#PCDATA|sub|super)*                          >

<!ELEMENT item       (effect*, chgdesc*, title?, dispcond?, graphic*)	>

<!ATTLIST item	     
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  itemnbr    NMTOKEN       #IMPLIED
	  %revatt;					>

<!ELEMENT dispcond   (remarks?, operation?, limitation?, placard?, maintenance?)>
<!ATTLIST dispcond	
	  category         CDATA        #IMPLIED
	  nbrins           CDATA        #IMPLIED
	  nbrreq           CDATA        #IMPLIED
	  maintenance      (YES|NO)      "NO"
	  operation        (YES|NO)      "NO"
		downgrade        CDATA        #IMPLIED
	  attr-rev        (YES|NO)      "NO"           >

<!ELEMENT remarks      (%text;|revision)*				>

<!ELEMENT placard	(%text;|revision)* 					>

<!ELEMENT maintenance	(title?,(%text;|act|graphic|revision)*) 					>
<!ATTLIST maintenance
          key           ID             #REQUIRED	>

<!ELEMENT operation	(%text;|act|graphic|revision)*					>
<!ATTLIST operation
          key           ID             #REQUIRED	>

<!ELEMENT limitation	(%text;|act|graphic|revision)* 					>
<!ATTLIST limitation
          key           ID             #REQUIRED	>

<!ELEMENT act (challenge,response+,comment*) >
<!ATTLIST act
          responsible (F|CF|PM|C|PF|SO) #IMPLIED>

<!ELEMENT challenge (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT response (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT comment (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT unlist    (unlitem+)                                    >
<!ATTLIST unlist
          bulltype  (NONE|BULLET|NDASH|MDASH
                     |DIAMOND|ASTERISK|DELTA
                     |SQUARE|SYSTEM1)                  'SYSTEM1'    >

<!ELEMENT unlitem   (para|note|example|exception|graphic|unlist)+ >

<!ELEMENT numlist   (numlitem+)                                   >
<!ATTLIST numlist
          numtype   (NNP|AUP|NNB|ALB|NNS|RUP|RLP|RUR|RLR|NNR
                      |AUR|ALR)                       'NNP'       >

<!ELEMENT numlitem  (%text;|graphic)+                             >


<!ELEMENT para      (#PCDATA  | grphcref | refext | refint
                         | sub | super | emphasis | revision)*       >

<!ELEMENT sub       (#PCDATA)                                     >
<!ELEMENT super     (#PCDATA)                                     >

<!ELEMENT emphasis (#PCDATA|emphasis)*                            >
<!ATTLIST emphasis
          role (bold|underline|italic)                 "italic"   >


<!ELEMENT title     (#PCDATA|sub|super|revision)*		  >
<!ELEMENT warning   (para | unlist | numlist)+                    >
<!ELEMENT note      (para | unlist | numlist)+                    >
<!ELEMENT caution   (para | unlist | numlist)+                    >
<!ELEMENT exception (para | unlist | numlist)+                    >
<!ELEMENT example   (para | unlist | numlist)+                    >

<!ELEMENT  ops		(ops_type, ops_message)>
<!ELEMENT  ops_type	(#PCDATA)	>
<!ELEMENT  ops_message	(#PCDATA)	>

<!ELEMENT effect    EMPTY                           >
<!ATTLIST effect
          effrg     CDATA                             "001999"
          efftext   CDATA                             "ALL"
          chg       (N|R|U|D)                         'U'         >


<!ELEMENT refext    (#PCDATA)                                     >
<!ATTLIST refext
          refman    CDATA                             #IMPLIED
          refspl    CDATA                             #IMPLIED
          refmodel  CDATA                             #IMPLIED
          docnbr    CDATA                             #IMPLIED
          refloc    CDATA                             #IMPLIED    >

<!ELEMENT refint    (#PCDATA)                                     >
<!ATTLIST refint
          reftype   CDATA                             #IMPLIED
          refid     IDREF                             #IMPLIED    >


<!ELEMENT grphcref  (#PCDATA | effect)*                           >
<!ATTLIST grphcref
          refid     IDREF                             #IMPLIED
          sheetnbr  CDATA                             #IMPLIED
          structid  CDATA                             #IMPLIED
          shownow   %yesorno;                         '0'         >

<!ELEMENT graphic   (effect?, title?, (sheet | revision)*)        >
<!ATTLIST graphic
          chapnbr     NMTOKEN                        #IMPLIED
          sectnbr     NMTOKEN                        #IMPLIED
          confnbr     NMTOKEN                        #IMPLIED
          %revatt;                                                >

<!ELEMENT sheet     (effect?, title?)                             >
<!ATTLIST sheet
          gnbr      ENTITY                            #IMPLIED
          filename  CDATA                             #IMPLIED
          sheetnbr  CDATA                             #IMPLIED
          imgarea   (AP|BP|CP|DL|EL|FP|GP|HL|IL)      #IMPLIED
          width     CDATA                             #IMPLIED
          height    CDATA                             #IMPLIED
          %revatt;                                                >


<!ELEMENT revision (#PCDATA|para|graphic|sheet|emphasis|revision|sub|super)* >
<!ATTLIST revision
          chg     (insert|delete|modify)              "modify"    >

<!ELEMENT chgdesc   (#PCDATA|emphasis|sub|super)*                 >



<!ENTITY % bodyatt "">
<!ENTITY % secur "">


<!ENTITY % yesorno 'CDATA'>
<!ENTITY % titles  'title?'>


<!ENTITY % paracon '#PCDATA'>

<!ENTITY % tbl.table.name       "(table|chart)">
<!ENTITY % tbl.table-titles.mdl "%titles;,">
<!ENTITY % tbl.table-main.mdl   "(tgroup+|graphic+)">
<!ENTITY % tbl.table.mdl        "%tbl.table-titles.mdl; %tbl.table-main.mdl;">
<!ENTITY % tbl.table.att        '
    tabstyle    CDATA           #IMPLIED
    tocentry    %yesorno;       #IMPLIED
    shortentry  %yesorno;       #IMPLIED
    orient      (port|land)     #IMPLIED
    pgwide      %yesorno;       #IMPLIED '>
<!ENTITY % tbl.tgroup.mdl       "colspec*,spanspec*,thead?,tfoot?,tbody">
<!ENTITY % tbl.tgroup.att       '
    tgroupstyle CDATA           #IMPLIED '>
<!ENTITY % tbl.hdft.mdl         "colspec*,row+">
<!ENTITY % tbl.row.mdl          "(entry|entrytbl)+">
<!ENTITY % tbl.entrytbl.mdl     "colspec*,spanspec*,thead?,tbody">
<!ENTITY % tbl.entry.mdl        "(%text;)*">

<!ELEMENT table (%tbl.table.mdl;)>
<!ATTLIST table
        frame           (top|bottom|topbot|all|sides|none)      #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        %tbl.table.att;
        %bodyatt;
        %secur;
>

<!ELEMENT tgroup (%tbl.tgroup.mdl;) >

<!ATTLIST tgroup
        cols            CDATA                                   #REQUIRED
        %tbl.tgroup.att;
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        %secur;
>

<!ELEMENT colspec EMPTY >

<!ATTLIST colspec
        colnum          CDATA                                   #IMPLIED
        colname         CDATA                                   #IMPLIED
        colwidth        CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
>

<!ELEMENT spanspec EMPTY >

<!ATTLIST spanspec
        namest          CDATA                                   #REQUIRED
        nameend         CDATA                                   #REQUIRED
        spanname        CDATA                                   #REQUIRED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
>

<!ELEMENT thead (%tbl.hdft.mdl;)>
<!ATTLIST thead
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT tfoot (%tbl.hdft.mdl;)>
<!ATTLIST tfoot
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT tbody (row+)>

<!ATTLIST tbody
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT row (%tbl.row.mdl;)>

<!ATTLIST row
        rowsep          %yesorno;                               #IMPLIED
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT entrytbl (%tbl.entrytbl.mdl;)>

<!ATTLIST entrytbl
        cols            CDATA                                   #REQUIRED
        %tbl.tgroup.att;
        colname         CDATA                                   #IMPLIED
        spanname        CDATA                                   #IMPLIED
        namest          CDATA                                   #IMPLIED
        nameend         CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        %secur;
>

<!ELEMENT entry (%tbl.entry.mdl;)*>

<!ATTLIST entry
        colname         CDATA                                   #IMPLIED
        namest          CDATA                                   #IMPLIED
        nameend         CDATA                                   #IMPLIED
        spanname        CDATA                                   #IMPLIED
        morerows        CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        rotate          %yesorno;                               #IMPLIED
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

=== skoma123/CMSTest/CMS/MEL/757/Working/UPS-757-MEL-00000720.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="27" chg="U" itemnbr="2" key="UPS-757-MEL-00000720" revdate="20080924" revnbr="65" sectnbr="21">
<title>Power Control Unit Monitor System (Including Pressure Differential
Sensors)</title>
<dispcond btb="YES" category="C" maintenance="YES" nbrins="1" nbrreq="0"
operation="NO">
<remarks>
<para>May be inoperative provided Power Control Unit Actuators are
verified to be operative by performing a single hydraulic system flight
controls check with each hydraulic system before each departure.</para>
</remarks>
<placard>
<para>Placard near EICAS "POWER CONTROL UNIT MONITOR INOP" and enter
item in Aircraft Deferred Item Log.</para>
</placard>
<maintenance key="UPS-757-MEL-00000721">
<note><para>The repetitive inspection required when this item is inoperative
must be documented in the Aircraft Logbook at the prescribed intervals.
 (Refer to GMM, Chapter 3, Section 6.)</para></note>
<para>Before each departure, perform a single hydraulic flight controls
check with each of the three hydraulic systems as follows:</para>
<warning><para>ENSURE PERSONNEL AND EQUIPMENT ARE CLEAR OF ALL CONTROL
SURFACES TO PREVENT INJURY OR DAMAGE.</para></warning>
<numlist>
<numlitem><para>Supply pressure to Left, Right and Center hydraulic
systems.</para></numlitem>
<numlitem><para>Center Electric Hydraulic Pump Switches.........................ON</para>
</numlitem>
<numlitem><para>Observe Center Electric Pump PRESS light(s) extinguished.</para>
<note><para>If the aircraft is using only the APU or ground power,
there is no power to the number 2 pump therefore the number 1 center
electric pump will come on and only the PRESS light for the number
1 pump will extinguish. </para></note>
</numlitem>
<numlitem><para>Left and Right Pump Switches.....................................OFF</para>
</numlitem>
<numlitem><para>Rudder check: Displace rudder in both directions while
observing rudder deflection on EICAS status display. Verify movement
in proper direction, and that deflection rate is normal (rate is non-normal
if control surface deflection lags significantly behind pilot input).</para>
<note><para>Hold the nose wheel steering tiller stationary during
rudder check to prevent nose wheel movement. </para></note>
</numlitem>
<numlitem><para>Elevator check: Set the stabilizer to 7 units. Displace
control column forward and aft while observing elevator deflection
on EICAS status display. Control column sweep should be accomplished
at a rate of 8-12 seconds for a full column sweep (from neutral to
full nose up to full nose down to neutral). Verify movement in proper
direction, and that deflection rate is normal (rate is non-normal
if control surface deflection lags significantly behind pilot input).
Also verify that both elevators track the column input and that there
is no significant disagreement between the two surfaces. Ensure that
each surface returns to neutral position when the column is returned
to neutral.</para>
<note><para>The SPOILERS light and message may illuminate if the control
wheel is displaced with only the center system hydraulics available.
The light will extinguish after the left and right hydraulic systems
are powered.</para></note>
</numlitem>
<numlitem><para>Center Electric Pump Switches....................................OFF</para>
</numlitem>
<numlitem><para>Left ENG or Left ELEC Pump Switch..........................ON</para>
</numlitem>
<numlitem><para>Observe appropriate Left Pump PRESS light extinguished.</para>
</numlitem>
<numlitem><para>Repeat steps 5 and 6.</para></numlitem>
<numlitem><para>Left ENG and Left ELEC Pump Switches...................OFF</para>
</numlitem>
<numlitem><para>Right ENG or Right ELEC Pump Switch....................ON</para>
</numlitem>
<numlitem><para>Observe appropriate Right Pump PRESS light extinguished.</para>
</numlitem>
<numlitem><para>Repeat steps 5 and 6.</para></numlitem>
<numlitem><para>Restore HYDRAULIC PANEL Pump Switch setting as required
and observe Pump PRESS lights are as appropriate.</para></numlitem>
<numlitem><para>Reset stabilizer to takeoff trim setting, as required.</para>
</numlitem>
<numlitem><para>Return aircraft to normal configuration. </para>
</numlitem>
</numlist>
</maintenance>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/757/Working/UPS757MELCDL20080527114925.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="21" chg="U" itemnbr="1-1" key="UPS757MELCDL20080527114925" revdate="20080924" revnbr="65" sectnbr="23">
<title>Return Air Grille &ndash; All Cargo Configuration</title>
<dispcond category="C" maintenance="YES" nbrins="16" nbrreq="15">
<remarks>
<para>One may be broken or missing provided:</para>
<numlist>
<numlitem><para>Broken or missing grille is located within a designated
area, and</para></numlitem>
<numlitem><para>Alternate procedures are established and used to cover
grille.</para></numlitem>
</numlist>
</remarks>
<placard>
<para>Placard next to upper EICAS screen "RETURN AIR GRILLE AT STA
____ BLOCKED" and enter item in Aircraft Deferred Item Log.</para>
</placard>
<maintenance key="UPS757MELCDL20080527115540">
<note><para>One Return Air Grille may be blocked off only in the following
area. (No other Return Air Grille may be blocked off):</para><para
>-STA 1260 to 1360 both left and right sides.</para>
<para>-STA 1600 to 1720 right side only.</para>
<para>-STA 1620 to 1720 left side only.</para>
<numlist>
<numlitem><para>Damages such as dents, cracks (minor nature) and cosmetic
conditions that do not allow any object larger than the nominal screen
vent hole size to pass thru into the air return box area are acceptable
for normal operation.</para></numlitem>
<numlitem><para>Severe damages that can allow objects larger than
the nominal screen vent holes to pass thru into the air return box
area, cause damage to personnel or equipment, or prevent the Return
Air Grille from performing as intended, must be corrected.</para>
</numlitem>
<numlitem><para>One severely damaged or missing Return Air Grille
located in the designated area may be blocked off with speed tape
or a panel that completely covers the grille area using standard SRM
procedures.</para></numlitem>
</numlist>
</note>
</maintenance>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/747/UPS747MEL20070815102816.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="26" chg="U" itemnbr="2-1" key="UPS747MEL20070815102816" revdate="20080827" revnbr="5" sectnbr="11">
<title>Engine Overheat Detection System &ndash; Detection Loop</title>
<dispcond category="C" nbrins="8" nbrreq="4" operation="NO">
<remarks>
<para>One loop per engine may be inoperative.</para>
</remarks>
<operation key="UPS747MEL20070815102817">
<note><para>The following EICAS message(s) may be displayed:</para>
<para>ENG ___ OVHT LP ___</para>
</note>
</operation>
<placard>
<para>Placard below Captain&rsquo;s PFD on P-1-1 panel: "___ ENGINE___
FIRE LOOP INOP". Enter Item in Aircraft Deferred Item Log.</para>
</placard>
</dispcond>
</item>
