=== skoma123/CMSTest/CMS/MEL/747 Rev51.0 2012_1_31/Working/melcdl.dtd
<?xml version="1.0" encoding="utf-8"?>
<!NOTATION GIF SYSTEM "GIF"                                       >
<!NOTATION TIF SYSTEM "TIF"                                       >
<!NOTATION JPG SYSTEM "JPG"                                       >

<!NOTATION PNG SYSTEM "PNG"                                       >
<!NOTATION cgm PUBLIC
"-//USA-DOD//NOTATION Computer Graphics Metafile//EN"             >
  
<!NOTATION ccitt4 PUBLIC
"-//USA-DOD//NOTATION CCITT Group 4 Facsimile//EN"                >

<!ENTITY % ATIeqn1 PUBLIC "-//ArborText//ENTITIES Equation1//EN//XML" "entities/ati-eqn1.ent">
<!ENTITY % ISOamsa PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Arrow Relations//EN//XML" "entities/iso-amsa.ent"  >
<!ENTITY % ISOamsb PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Binary Operators//EN//XML" "entities/iso-amsb.ent"  >
<!ENTITY % ISOamsc PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Delimiters//EN//XML" "entities/iso-amsc.ent"  >
<!ENTITY % ISOamsn PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Negated Relations//EN//XML" "entities/iso-amsn.ent"  >
<!ENTITY % ISOamso PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Ordinary//EN//XML" "entities/iso-amso.ent"  >
<!ENTITY % ISOamsr PUBLIC "ISO 8879:1986//ENTITIES Added Math Symbols: Relations//EN//XML" "entities/iso-amsr.ent"  >
<!ENTITY % ISObox  PUBLIC "ISO 8879:1986//ENTITIES Box and Line Drawing//EN//XML" "entities/iso-box.ent"  >
<!ENTITY % ISOcyr1 PUBLIC "ISO 8879:1986//ENTITIES Russian Cyrillic//EN//XML" "entities/iso-cyr1.ent"  >
<!ENTITY % ISOcyr2 PUBLIC "ISO 8879:1986//ENTITIES Non-Russian Cyrillic//EN//XML" "entities/iso-cyr2.ent"  >
<!ENTITY % ISOdia  PUBLIC "ISO 8879:1986//ENTITIES Diacritical Marks//EN//XML" "entities/iso-dia.ent"  >
<!ENTITY % ISOgrk1 PUBLIC "ISO 8879:1986//ENTITIES Greek Letters//EN//XML" "entities/iso-grk1.ent"  >
<!ENTITY % ISOgrk2 PUBLIC "ISO 8879:1986//ENTITIES Monotoniko Greek//EN//XML" "entities/iso-grk2.ent"  >
<!ENTITY % ISOgrk3 PUBLIC "ISO 8879:1986//ENTITIES Greek Symbols//EN//XML" "entities/iso-grk3.ent"  >
<!ENTITY % ISOgrk4 PUBLIC "ISO 8879:1986//ENTITIES Alternative Greek Symbols//EN//XML" "entities/iso-grk4.ent"  >
<!ENTITY % ISOlat1 PUBLIC "ISO 8879:1986//ENTITIES Added Latin 1//EN//XML" "entities/iso-lat1.ent"  >
<!ENTITY % ISOlat2 PUBLIC "ISO 8879:1986//ENTITIES Added Latin 2//EN//XML" "entities/iso-lat2.ent"  >
<!ENTITY % ISOnum  PUBLIC "ISO 8879:1986//ENTITIES Numeric and Special Graphic//EN//XML" "entities/iso-num.ent"  >
<!ENTITY % ISOpub  PUBLIC "ISO 8879:1986//ENTITIES Publishing//EN//XML" "entities/iso-pub.ent"  >
<!ENTITY % ISOtech PUBLIC "ISO 8879:1986//ENTITIES General Technical//EN//XML" "entities/iso-tech.ent"  >
<!ENTITY % HTMLlat1x PUBLIC "-//W3C//ENTITIES Latin1//EN//HTML" "entities/HTMLlat1x.ent" >
<!ENTITY % HTMLsymbolx PUBLIC "-//W3C//ENTITIES Symbols//EN//HTML" "entities/HTMLsymbolx.ent">
<!ENTITY % HTMLspecialx PUBLIC "-//W3C//ENTITIES Special//EN//HTML" "entities/HTMLspecialx.ent">

%ATIeqn1; %ISOamsa; %ISOamsb; %ISOamsc; %ISOamsn; %ISOamso; %ISOamsr; %ISObox; %ISOcyr1; %ISOcyr2;
%ISOdia; %ISOgrk1; %ISOgrk2; %ISOgrk3; %ISOgrk4; %ISOlat1; %ISOlat2; %ISOnum; %ISOpub; %ISOtech;
%HTMLlat1x; %HTMLsymbolx; %HTMLspecialx;

<!ENTITY   % w.c     "(warning*,caution*)"                        >

<!ENTITY   % text
       "para|table|unlist|numlist|glosdata|
         warning|caution|note|exception|example|ops"              >

<!ENTITY % revatt     "chg          (N|R|U|D)       'N'
                       key           ID             #REQUIRED
                       revnbr        CDATA          #REQUIRED
                       revdate       NMTOKEN        #REQUIRED" >

<!ENTITY % yesorno    "NMTOKEN" >
<!ELEMENT melcdl         (legalntc?, revdata?, mel, dmp, cdl)                  >

<!ATTLIST melcdl  
	  model          CDATA          #REQUIRED
          mantype       (MELCDL)        'MELCDL'
          oidate         NMTOKEN        #REQUIRED
          tsn            CDATA          #REQUIRED
          docnbr         CDATA          #IMPLIED
          lang           CDATA          #REQUIRED
          cus            CDATA          #REQUIRED
          spl            CDATA          #IMPLIED
	  chg          (N|R|U|D)        'N'
          key           ID              #REQUIRED
          revdate       NMTOKEN         #REQUIRED
          faadate       NMTOKEN         #IMPLIED
          mmelrevnbr    CDATA           #REQUIRED                    >

<!ELEMENT legalntc  (chgdesc*, proptary?, cpyrght?, geninfo?)     >
<!ATTLIST legalntc
          key           ID             #REQUIRED                  >

<!ELEMENT proptary  (title?, para+)                               >
<!ELEMENT cpyrght   (year?, holder+)                              >
<!ELEMENT year      (#PCDATA)                                     >
<!ELEMENT holder    (#PCDATA)                                     >
<!ELEMENT geninfo   (title?,(%text;)+)           	          >


<!ELEMENT revdata (coverpage?, recrev, transmittal)               >
<!ELEMENT coverpage  (para+)           	                  >  
<!ELEMENT recrev  (title?,(%text;)+)           	                  >
<!ATTLIST recrev   chg          (N|R|U|D)       'N'
                   revdate       NMTOKEN        #REQUIRED         >

<!ELEMENT transmittal  (title?,(%text;|graphic)+)           	  >

<!ELEMENT mel  (title, mfmatr, chapter*)                             >

<!ATTLIST mel
 	  %revatt;				                     >

<!ELEMENT cdl  (title, mfmatr?, chapter*)                            >

<!ATTLIST cdl
 	  %revatt;				                     >

<!ELEMENT dmp  (title, mfmatr?)                                      >

<!ATTLIST dmp
 	  %revatt;				                     >


<!ELEMENT mfmatr (section+)               		             >

<!ATTLIST mfmatr       
	  %revatt;					             >

<!ELEMENT chapter  (chgdesc*, title, ecam?)	     >

<!ATTLIST chapter	
	  chapnbr     NMTOKEN      #REQUIRED
	  %revatt;				>

<!ELEMENT ecam		(chgdesc*, ecam_group+)                      >

<!ATTLIST ecam		
	  chapnbr     NMTOKEN      #REQUIRED
 	  %revatt;				                     >
          
<!ELEMENT ecam_group	(fltmsg_category, ecam_warning+)	     >

<!ELEMENT fltmsg_category  (#PCDATA) 				     >
	  
<!ELEMENT ecam_warning	(ecam_fltmsg, ecam_dispcond, ecam_remark)    >

<!ELEMENT ecam_fltmsg	(#PCDATA) 				     >
								
<!ELEMENT ecam_dispcond	(para+) 			             >
									
<!ELEMENT ecam_remark	(%text;)+ 			             >

<!ELEMENT section    (chgdesc*,  title?, (item+ | textset+ 
                                            | (cdlblk, note*)+))       >
<!ATTLIST section	
	  chapnbr	NMTOKEN	  #REQUIRED
	  sectnbr	NMTOKEN	  #REQUIRED
	  %revatt;				>


<!ELEMENT textset    (chgdesc*, title?, (%text;|graphic|textgrp|revision)+) >
<!ATTLIST textset
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  textsetnbr NMTOKEN       #REQUIRED
          %revatt;		             >
<!ELEMENT textgrp   (title?,(%text;|graphic|textgrp|revision)+)   >
<!ATTLIST textgrp
          tip       %yesorno;                         #IMPLIED   
          textgrpnbr NMTOKEN                          #IMPLIED    >

<!ELEMENT cdlblk    (chgdesc*, title?, remarks, (%text;|act | graphic 
                              | textgrp | revision)*)   >
<!ATTLIST cdlblk
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  %revatt;
	  blknbr     NMTOKEN       #IMPLIED
	  qtyreq     CDATA         #IMPLIED
	  attr-rev   (YES|NO)      "NO"                           >
																  

<!ELEMENT glosdata  (term, def)                                   >
<!ELEMENT term      (#PCDATA|sub|super)*                          >
<!ELEMENT def       (#PCDATA|sub|super)*                          >

<!ELEMENT item       (effect*, chgdesc*, title?, dispcond?, graphic*)	>

<!ATTLIST item	     
	  chapnbr    NMTOKEN       #REQUIRED
	  sectnbr    NMTOKEN       #REQUIRED
	  itemnbr    NMTOKEN       #IMPLIED
	  %revatt;					>

<!ELEMENT dispcond   (remarks?, operation?, limitation?, placard?, maintenance?)>
<!ATTLIST dispcond	
	  category         CDATA        #IMPLIED
	  nbrins           CDATA        #IMPLIED
	  nbrreq           CDATA        #IMPLIED
	  maintenance      (YES|NO)      "NO"
	  operation        (YES|NO)      "NO"
		downgrade        CDATA        #IMPLIED
	  attr-rev        (YES|NO)      "NO"           >

<!ELEMENT remarks      (%text;|revision)*				>

<!ELEMENT placard	(%text;|revision)* 					>

<!ELEMENT maintenance	(title?,(%text;|act|graphic|revision)*) 					>
<!ATTLIST maintenance
          key           ID             #REQUIRED	>

<!ELEMENT operation	(%text;|act|graphic|revision)*					>
<!ATTLIST operation
          key           ID             #REQUIRED	>

<!ELEMENT limitation	(%text;|act|graphic|revision)* 					>
<!ATTLIST limitation
          key           ID             #REQUIRED	>

<!ELEMENT act (challenge,response+,comment*) >
<!ATTLIST act
          responsible (F|CF|PM|C|PF|SO) #IMPLIED>

<!ELEMENT challenge (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT response (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT comment (#PCDATA|sub|super|emphasis|revision)*  >

<!ELEMENT unlist    (unlitem+)                                    >
<!ATTLIST unlist
          bulltype  (NONE|BULLET|NDASH|MDASH
                     |DIAMOND|ASTERISK|DELTA
                     |SQUARE|SYSTEM1)                  'SYSTEM1'    >

<!ELEMENT unlitem   (para|note|example|exception|graphic|unlist)+ >

<!ELEMENT numlist   (numlitem+)                                   >
<!ATTLIST numlist
          numtype   (NNP|AUP|NNB|ALB|NNS|RUP|RLP|RUR|RLR|NNR
                      |AUR|ALR)                       'NNP'       >

<!ELEMENT numlitem  (%text;|graphic)+                             >


<!ELEMENT para      (#PCDATA  | grphcref | refext | refint
                         | sub | super | emphasis | revision)*       >

<!ELEMENT sub       (#PCDATA)                                     >
<!ELEMENT super     (#PCDATA)                                     >

<!ELEMENT emphasis (#PCDATA|emphasis)*                            >
<!ATTLIST emphasis
          role (bold|underline|italic)                 "italic"   >


<!ELEMENT title     (#PCDATA|sub|super|revision)*		  >
<!ELEMENT warning   (para | unlist | numlist)+                    >
<!ELEMENT note      (para | unlist | numlist)+                    >
<!ELEMENT caution   (para | unlist | numlist)+                    >
<!ELEMENT exception (para | unlist | numlist)+                    >
<!ELEMENT example   (para | unlist | numlist)+                    >

<!ELEMENT  ops		(ops_type, ops_message)>
<!ELEMENT  ops_type	(#PCDATA)	>
<!ELEMENT  ops_message	(#PCDATA)	>

<!ELEMENT effect    EMPTY                           >
<!ATTLIST effect
          effrg     CDATA                             "001999"
          efftext   CDATA                             "ALL"
          chg       (N|R|U|D)                         'U'         >


<!ELEMENT refext    (#PCDATA)                                     >
<!ATTLIST refext
          refman    CDATA                             #IMPLIED
          refspl    CDATA                             #IMPLIED
          refmodel  CDATA                             #IMPLIED
          docnbr    CDATA                             #IMPLIED
          refloc    CDATA                             #IMPLIED    >

<!ELEMENT refint    (#PCDATA)                                     >
<!ATTLIST refint
          reftype   CDATA                             #IMPLIED
          refid     IDREF                             #IMPLIED    >


<!ELEMENT grphcref  (#PCDATA | effect)*                           >
<!ATTLIST grphcref
          refid     IDREF                             #IMPLIED
          sheetnbr  CDATA                             #IMPLIED
          structid  CDATA                             #IMPLIED
          shownow   %yesorno;                         '0'         >

<!ELEMENT graphic   (effect?, title?, (sheet | revision)*)        >
<!ATTLIST graphic
          chapnbr     NMTOKEN                        #IMPLIED
          sectnbr     NMTOKEN                        #IMPLIED
          confnbr     NMTOKEN                        #IMPLIED
          %revatt;                                                >

<!ELEMENT sheet     (effect?, title?)                             >
<!ATTLIST sheet
          gnbr      ENTITY                            #IMPLIED
          filename  CDATA                             #IMPLIED
          sheetnbr  CDATA                             #IMPLIED
          imgarea   (AP|BP|CP|DL|EL|FP|GP|HL|IL)      #IMPLIED
          width     CDATA                             #IMPLIED
          height    CDATA                             #IMPLIED
          %revatt;                                                >


<!ELEMENT revision (#PCDATA|para|graphic|sheet|emphasis|revision|sub|super)* >
<!ATTLIST revision
          chg     (insert|delete|modify)              "modify"    >

<!ELEMENT chgdesc   (#PCDATA|emphasis|sub|super)*                 >



<!ENTITY % bodyatt "">
<!ENTITY % secur "">


<!ENTITY % yesorno 'CDATA'>
<!ENTITY % titles  'title?'>


<!ENTITY % paracon '#PCDATA'>

<!ENTITY % tbl.table.name       "(table|chart)">
<!ENTITY % tbl.table-titles.mdl "%titles;,">
<!ENTITY % tbl.table-main.mdl   "(tgroup+|graphic+)">
<!ENTITY % tbl.table.mdl        "%tbl.table-titles.mdl; %tbl.table-main.mdl;">
<!ENTITY % tbl.table.att        '
    tabstyle    CDATA           #IMPLIED
    tocentry    %yesorno;       #IMPLIED
    shortentry  %yesorno;       #IMPLIED
    orient      (port|land)     #IMPLIED
    pgwide      %yesorno;       #IMPLIED '>
<!ENTITY % tbl.tgroup.mdl       "colspec*,spanspec*,thead?,tfoot?,tbody">
<!ENTITY % tbl.tgroup.att       '
    tgroupstyle CDATA           #IMPLIED '>
<!ENTITY % tbl.hdft.mdl         "colspec*,row+">
<!ENTITY % tbl.row.mdl          "(entry|entrytbl)+">
<!ENTITY % tbl.entrytbl.mdl     "colspec*,spanspec*,thead?,tbody">
<!ENTITY % tbl.entry.mdl        "(%text;)*">

<!ELEMENT table (%tbl.table.mdl;)>
<!ATTLIST table
        frame           (top|bottom|topbot|all|sides|none)      #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        %tbl.table.att;
        %bodyatt;
        %secur;
>

<!ELEMENT tgroup (%tbl.tgroup.mdl;) >

<!ATTLIST tgroup
        cols            CDATA                                   #REQUIRED
        %tbl.tgroup.att;
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        %secur;
>

<!ELEMENT colspec EMPTY >

<!ATTLIST colspec
        colnum          CDATA                                   #IMPLIED
        colname         CDATA                                   #IMPLIED
        colwidth        CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
>

<!ELEMENT spanspec EMPTY >

<!ATTLIST spanspec
        namest          CDATA                                   #REQUIRED
        nameend         CDATA                                   #REQUIRED
        spanname        CDATA                                   #REQUIRED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
>

<!ELEMENT thead (%tbl.hdft.mdl;)>
<!ATTLIST thead
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT tfoot (%tbl.hdft.mdl;)>
<!ATTLIST tfoot
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT tbody (row+)>

<!ATTLIST tbody
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT row (%tbl.row.mdl;)>

<!ATTLIST row
        rowsep          %yesorno;                               #IMPLIED
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

<!ELEMENT entrytbl (%tbl.entrytbl.mdl;)>

<!ATTLIST entrytbl
        cols            CDATA                                   #REQUIRED
        %tbl.tgroup.att;
        colname         CDATA                                   #IMPLIED
        spanname        CDATA                                   #IMPLIED
        namest          CDATA                                   #IMPLIED
        nameend         CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        %secur;
>

<!ELEMENT entry (%tbl.entry.mdl;)*>

<!ATTLIST entry
        colname         CDATA                                   #IMPLIED
        namest          CDATA                                   #IMPLIED
        nameend         CDATA                                   #IMPLIED
        spanname        CDATA                                   #IMPLIED
        morerows        CDATA                                   #IMPLIED
        colsep          %yesorno;                               #IMPLIED
        rowsep          %yesorno;                               #IMPLIED
        align           (left|right|center|justify|char)        #IMPLIED
        char            CDATA                                   #IMPLIED
        charoff         CDATA                                   #IMPLIED
        rotate          %yesorno;                               #IMPLIED
        valign          (top|middle|bottom)                     #IMPLIED
        %secur;
>

=== skoma123/CMSTest/CMS/MEL/757/Working/UPS-757-MEL-00001082.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="36" chg="U" itemnbr="1" key="UPS-757-MEL-00001082" revdate="20091120" revnbr="67" sectnbr="11">
<title>ENG BLEED Pressure Regulating and Shutoff Valves  (PRSOV) (L
&amp; R)</title>
<dispcond attr-rev="NO" btb="NO" category="C" maintenance="YES"
nbrins="2" nbrreq="1" operation="NO">
<remarks>
<para>Except for ER operations beyond 120 minutes, one may be inoperative
provided:</para>
<numlist>
<numlitem><para>PRSOV is closed, </para></numlitem>
<numlitem><para>Associated engine BLEED switch remains OFF,</para>
</numlitem>
<numlitem><para>Aircraft is not operated in known or forecast icing
conditions, </para></numlitem>
<numlitem><para>Remaining (opposite) engine bleed system and its associated
pack are operative, and</para></numlitem>
<numlitem><para>Aircraft remains at or below FL350.</para></numlitem>
</numlist>
</remarks>
<limitation key="UPS-757-MEL-00001084">
<numlist>
<numlitem><para>Operations into known or forecast icing conditions
is prohibited. </para></numlitem>
<numlitem><para>Aircraft remains at or below FL350.</para></numlitem>
</numlist>
</limitation>
<placard>
<para>Placard applicable BLEED AIR L or R ENG switchlight located
on Bleed Air Supply Module (M10259) on P5 panel "INOP" and enter item
in Aircraft Deferred Item Log.</para>
</placard>
<maintenance key="UPS-757-MEL-00001083">
<numlist>
<numlitem><para>Notify Flight Dispatch.  Aircraft operation, procedures
and flight planning may be affected.</para></numlitem>
<numlitem><para>Press BLEED AIR L and R ENG switchlight on pilots
overhead P5 panel to OFF.  Verify OFF lights come on.</para></numlitem>
<numlitem><para>If OFF light does not come on:</para><para><emphasis
role="bold"> PW ENGINE</emphasis></para>
<numlist>
<numlitem><para>Open applicable engine right core cowl (418R Left
engine, 428AR Right engine).</para></numlitem>
<numlitem><para>Rotate manual override hex nut on pressure regulating
and shutoff valve clockwise until  the  poppet valve lever falls into
the lock arm assembly notch.  The word "LOCKED" should be visible
on the valve body beneath the cam.  Ensure the poppet valve lever
is not in the detent position. </para></numlitem>
<numlitem><para>Close engine core cowl.</para></numlitem>
</numlist>
</numlitem>
</numlist>
<graphic chapnbr="36" chg="U" key="UPS757DMPFIG3601" revdate="20080924"
revnbr="65" sectnbr="11">
<title>PRSOV</title>
<sheet chg="U" gnbr="DMP_CH_36_Page_1" key="UPSDMP_CH_36_Page_1"
revdate="20080924" revnbr="65">
<title>P&amp;W ENGINE</title>
</sheet>
</graphic>
<numlist>
<numlitem><para><emphasis role="bold">RB211 ENGINE</emphasis></para>
<numlist>
<numlitem><para>Open applicable strut pressure relief door (433LR
Right engine, 433LL Left engine).</para></numlitem>
<numlitem><para>Rotate the manual override hex nut on the pressure
regulating and shutoff valve clockwise until the poppet valve lever
falls into the lock arm assembly notch.  The word "LOCKED" should
be visible on the valve body beneath the cam.  Ensure the poppet valve
lever is not in the detent position. </para></numlitem>
<numlitem><para>Close strut pressure relief door.</para></numlitem>
</numlist>
</numlitem>
</numlist>
<graphic chapnbr="36" chg="U" key="UPS757DMPFIG3602" revdate="20080924"
revnbr="65" sectnbr="11">
<title>PRSOV</title>
<sheet chg="U" gnbr="DMP_CH_36_Page_2" key="UPSDMP_CH_36_Page_2"
revdate="20080924" revnbr="65">
<title>RB211 ENGINE</title>
</sheet>
</graphic>
</maintenance>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/747/Staging/UPS747MEL20070815103710.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="29" chg="U" itemnbr="2-2" key="UPS747MEL20070815103710" revdate="20100707" revnbr="8" sectnbr="11">
<!--Per email that Tim sent 1/14/10 Rev 8-->
<title>Demand Hydraulic Pumps &ndash; No. 2 or No. 3 Demand Pump Systems</title>
<dispcond attr-rev="NO" category="C" maintenance="YES" nbrins="2"
nbrreq="1" operation="NO" btb="YES">
<remarks>
<para>One may be inoperative deactivated provided demand pumps 1 and
4 are operative.</para>
</remarks>
<operation key="UPS747MEL20070815103711">
<note><para>The following EICAS message(s) may be displayed:</para>
<para>HYD PRESS DEM ___</para>
</note>
</operation>
<placard>
<para>Placard adjacent to associated #2 or #3 Demand pump switch:
"INOP". Enter item in Aircraft Deferred Item Log.</para>
</placard>
<maintenance key="UPS747MEL20070815103712">
<numlist>
<numlitem><para>Accomplish Dispatch Maintenance Procedure <refint
refid="UPS747MEL20070815103659" reftype="MNT">29-11-2-1</refint>.</para>
</numlitem>
</numlist>
</maintenance>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/747/Working/UPS747MEL20070815101923.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE item PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<item chapnbr="21" chg="U" itemnbr="13" key="UPS747MEL20070815101923" revdate="20080827" revnbr="5" sectnbr="61">
<title>Flight Deck Flow Regulating Valve </title>
<dispcond category="C" maintenance="YES" nbrins="1" nbrreq="0"
operation="NO" btb="YES">
<remarks>
<para>May be inoperative secured open.</para>
</remarks>
<operation key="UPS747MEL20070815101924">
<note><para>The following EICAS message(s) may be displayed:</para>
<para>ZONE TEMP</para>
</note>
<numlist>
<numlitem><para>To maintain normal flow rate and noise level during
all flight phases.  Position LOWER LOBE CARGO COND AIR FLOW RATE selector
to either FWD HIGH, AFT HIGH, or BOTH LOW.</para></numlitem>
</numlist>
</operation>
<placard>
<para>Placard adjacent to the TRIM AIR switch "FLIGHT DECK FLOW REGULATING
VLV INOP".  Enter item in Aircraft Deferred Item Log.</para>
</placard>
<maintenance key="UPS747MEL20070815101925">
<numlist>
<numlitem><para>To secure Flight Deck Flow Regulating Valve in the
open position do the following:</para>
<numlist>
<numlitem><para>Open the P6 panel ZONE TEMP CONT AC and ZONE TEMP
CONT DC circuit breakers.</para></numlitem>
<numlitem><para>Locate the Flight Deck Flow Regulating valve under
the main deck floor at STA 1130, WL 194, LBL 45.</para>
<numlist>
<numlitem><para>Disconnect, cap, and stow the valve&rsquo;s electrical
connector. </para></numlitem>
<numlitem><para>Manually position the valve in the OPEN position (requires
an Allen wrench).</para></numlitem>
</numlist>
</numlitem>
<numlitem><para>Close the P6 panel ZONE TEMP CONT AC and ZONE TEMP
CONT DC circuit breakers.</para></numlitem>
</numlist>
</numlitem>
<numlitem><para>With the flight deck flow regulating valve secured
open, status message ZONE TEMP will remain displayed.</para></numlitem>
<numlitem><para>Status message ZONE TEMP may remain displayed if the
flight deck flow regulating valve is secured open.</para></numlitem>
</numlist>
</maintenance>
</dispcond>
</item>

=== skoma123/CMSTest/CMS/MEL/757/Working/UPS-757-MEL-00001556.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cdlblk PUBLIC "-//UPS//DTD MELCDL-REV1//EN" "melcdl.dtd">
<cdlblk blknbr="1" chapnbr="71" chg="U" key="UPS-757-MEL-00001556" qtyreq="16" revdate="20080924" revnbr="65" sectnbr="00">
<title>(RR) POWER PLANT TRAILING EDGE SEAL</title>
<remarks>
<para>One per engine may be missing provided the performance and weights
are reduced by:</para>
<table frame="none">
<tgroup cols="3">
<colspec align="left" colname="col1" colwidth="1.01*"/>
<colspec align="right" colname="col2" colwidth="0.62*"/>
<colspec align="left" colname="COLSPEC0" colwidth="1.74*"/>
<tbody>
<row>
<entry colsep="0" rowsep="0">
<para>Takeoff and Landing:</para>
</entry>
<entry colsep="0" rowsep="0">
<para>&ndash;</para>
</entry>
<entry colsep="0" rowsep="0">
<para>193 lbs/seal</para>
</entry>
</row>
<row>
<entry colsep="0" rowsep="0">
<para>En route Climb:</para>
</entry>
<entry colsep="0" rowsep="0">
<para>&ndash;</para>
</entry>
<entry colsep="0" rowsep="0">
<para>287 lbs/seal</para>
</entry>
</row>
<row>
<entry align="center" colsep="0" nameend="COLSPEC0" namest="col1"
rowsep="0">
<para>(Fuel burn increase 0.20%)</para>
</entry>
</row>
</tbody>
</tgroup>
</table>
</remarks>
</cdlblk>
